name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: Upload package artifact
      uses: actions/upload-artifact@v1
      with:
        name: target
        path: target/

  package:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Download artifact
      uses: actions/download-artifact@master
      with:
        name: target
    - name: Docker login
      uses: actions/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Docker build
      uses: actions/docker/cli@master
      with:
        args: "build -t konrader/eon-consumption ."
