name: Java CI

on: [push]

jobs:
  build:
    name: Maven build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: Extract version
      run: mvn help:evaluate --file pom.xml -Dexpression=project.version -q -DforceStdout > target/version.txt
    - name: Include Docker file
      run: cp Dockerfile target/
    - name: Upload package artifact
      uses: actions/upload-artifact@v1
      with:
        name: target
        path: target/

  docker:
    name: Docker build and publish
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@master
      with:
        name: target
    - name: Read version
      run: cat target/version.txt
    - name: Docker build
      uses: actions/docker/cli-multi@master
      with:
        args:
        - "build -f target/Dockerfile -t konrader/eon-consumption ."
        - "tag konrader/eon-consumption:latest konrader/eon-consumption:$(cat target/version.txt)"
    - name: Docker tag
      run: docker tag konrader/eon-consumption:latest konrader/eon-consumption:$(cat target/version.txt)
    - name: Docker login
      uses: actions/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: DockerHub publish
      run: docker push konrader/eon-consumption
